### ISSUE TITLE
Fast Piantissimo in Fast IWs

### ISSUE THREAD

**Issue by pyorot** [BitPatty/gctGenerator#126]
**Feature Request**  
Requesting that a code be made to force fastest Piantissimo on all versions.
Both standalone and integrated into the Stage List Loader, used in Fast IW presets.
Please also document the time difference of and criteria for unlocking the Piantissimo patterns.

**Usage**  
In my use case, with the [Fast IW IGT memory autosplitter script](https://pastebin.com/DRtVGAAM), this would remove the need to mess about with memory cards and have to menu to Save and Continue in all Fast IWs including Piantissimo. This would make it very easy to run Fast IWs on emulator, by running the game with Stage Loader and QFT cheat codes (make a save-state for each world for convenience), and having the autosplitter automatically follow the stages and resets.

**Further Development**  
I'd recommend standardising QFT to conform to IL timing and encouraging this practice method with cumulative-IGT leaderboards going forward. On console, Fast IWs still work but require manually adding up the IL times to get IWs. I'd recommend integrating all this into a Fast IW romhack down the line, to save having to make a save-state with the correct set of cheat codes for each IW.

**Comment by BitPatty** [comment]
I once evaluated the list of thresholds in PAL, which I extracted from the respective piantissimo script files on the ISO, would need to confirm whether it's the same value for all versions. 

![image](https://user-images.githubusercontent.com/11077852/200513443-f8e6bad6-b7df-4416-8206-f776985be6cf.png)

I can look into this unless someone else wants to work on this.

> I'd recommend standardising QFT to conform to IL timing and encouraging this practice method with cumulative-IGT leaderboards going forward. On console, Fast IWs still work but require manually adding up the IL times to get IWs. I'd recommend integrating all this into a Fast IW romhack down the line, to save having to make a save-state with the correct set of cheat codes for each IW.

@QbeRoot @sup39  This is your area of expertise

**Comment by QbeRoot** [comment]
I've been in touch with the IL mod team about adjusting QFT, then found that the public version of the code wasn't where I expected it to be, so my bucket list is to merge those changes with my asm source, release, and change some things so codes can stay in Codes.xml without missing out on customization.

As for fast IWs, we could assign them to C stick + X + Y or something, but button combos and permanent on-screen text will only get us so far and it might be time to start making a full practice hack with a proper menu where users could mute/unmute BGM, select Chomp patterns, toggle the p/a/s displays individually, etc. From the dev side, we wouldn't have to worry so much about code size or making sure that codes integrate correctly while also being independent from each other. Of course the big downside would be the setup/update complexity (TTYD uses an ACE save file which Sunshine only gets on PAL) but we could just have the hack fetch code from its own save file, which would be different from the vanilla game if we change the game ID. Or we could use the broadband adapter which both Dolphin and Nintendont support, but I haven't found documentation about it so that'll be a big undertaking.

**Comment by pyorot** [comment]
As far as making a hack goes, I suggest making a patcher in the style of a randomiser. In the past, I would’ve recommended inquiring into Wind Waker Rando’s tools but dunno if that’s moved on.

But that’s all I’ll say about that cos I know you get distracted by the big picture 😏 tbh fast IWs already work very well on emulator and a fast Piantissimo cheat code would fix most of what’s bad, hence me making this issue.

**Comment by BitPatty** [comment]
A while ago I was considering a Nintendont fork dedicated to SMS practice, with a custom cheat menu within application itself (codes being cached on the SD Card / Updated from the Codes.xml via HTTP if desired).

This way people could still play from original Disk while at the same time having the flexibility to toggle codes without a third app (e.g. GCM). This would be very accessible / easy to set up and runners (and especially newcomers) wouldn't have to deal with the complexity of creating / applying patches etc.

**Comment by BitPatty** [comment]
> Of course the big downside would be the setup/update complexity (TTYD uses an ACE save file which Sunshine only gets on PAL) but we could just have the hack fetch code from its own save file, which would be different from the vanilla game if we change the game ID.

> Or we could use the broadband adapter which both Dolphin and Nintendont support, but I haven't found documentation about it so that'll be a big undertaking.

While both options would be extremely interesting from a technical perspective I feel they would both require a ton of analysis and implementation/optimization effort.

And even if one of them ends up working, loading and applying those patches on the fly *could* cause undesired side effects on load times, memory management, game behavior etc. in addition to the extra setup. That's probably not an issue for randomizers but for runs it might be. 

Of course that's all just speculation from my end but I don't think it's gonna be that "easy".

> Or we could use the broadband adapter

Note that even though Nintendont does support BBA it applies different patches based on which game wants to use the BBA functionality, so that may also require a modification of Nintendont itself.

Furthermore, the Wii only supports legacy Wi-Fi protocols that can affect other devices on the network and even needs to be enabled manually on modern routers.

**Comment by sup39** [comment]
I figured out a way to [read custom save file](https://github.com/sup39/SMS-ReadFile/blob/main/ReadFile.c). I'm not sure if this method causes any side effect, but I believe even if it does, it shouldn't be too difficult to solve since this code does not use the heap nor implement some low level features but calling existing functions like how the game read the normal save file.

If this method works well, we can combine all features into a single gci file and ask the users to install it with GCMM, which shouldn't be too difficult to perform. In addition, it should be possible to store user's configuration to save file.

**Comment by BitPatty** [comment]
Nice! What's the ready flag for?

**Comment by sup39** [comment]
Currently I extract the 06/07 codes that write to 817Fxxxx into gci file and leave the 04 codes (bl from original function to practice code functions placed in 817Fxxxx) in gct file. In order to make sure the practice code functions are loaded when the 04 codes applied, I wrap the 04 codes with a condition that checks if the ready flag is 1.

This is just a temporary solution. In the future, we may consider to do the 04 codes ourselves in a function loaded from the save file.

**Comment by QbeRoot** [comment]
Fast Piantissimo is now available for all versions on the generator!

@BitPatty 
> And even if one of them ends up working, loading and applying those patches on the fly could cause undesired side effects on load times, memory management, game behavior etc. in addition to the extra setup. That's probably not an issue for randomizers but for runs it might be.
I don't think it would be such a problem if the updates only ran on boot up or even on user prompt, but yeah we're not anywhere close to auto-updates anyway

**Comment by BitPatty** [comment]
@sup39 
> This is just a temporary solution. In the future, we may consider to do the 04 codes ourselves in a function loaded from the save file.

Makes me think, wouldn't only RAM fill codes work with this? Since 2x and 3x require the original state of the overwritten (stack) section to be restored if not longer applied.

@QbeRoot 
> I don't think it would be such a problem if the updates only ran on boot up or even on user prompt, but yeah we're not anywhere close to auto-updates anyway

I mean in the end it (hopefully) mostly depends on the complexity of the codes that are being applied.

**Comment by pyorot** [comment]
> Fast Piantissimo is now available for all versions on the generator!

Cheers, boss. I did some testing to time the difference between the fastest and slowest patterns. It wasn't a perfect test because the animations are janky and Piantissimo lands in different places at different angles, though I kept Mario's position and angle consistent via the restore position practice code. So real-world results may vary slightly depending on where Mario stands. Timed from (start) textbox close to (finish) textbox open:

| | g5 | n5 | q2 |
| - | - | - | - |
| slow | 34.267 | 36.837 | 28.529 |
| fast | 20.920 | 23.056 | 19.019 |
| diff | 13.347 | 13.781 |  9.510 |

In each case, the turning animation (from when Mario/Piantissimo/camera moves until finish textbox opens) is 25f–30f.

So yeah, that's everything except I think the new code should also be listed in the stage loader options.

And it might be nice to open a new issue for the practice mod design :)

**Comment by BitPatty** [comment]
> I think the new code should also be listed in the stage loader options.

Not sure if I misunderstand, but that's redundant as the code selection is merged with stage loader when downloading. Remove Dialogue / FMV skip are special due to the conditionals.

**Comment by pyorot** [comment]
I thought the design of the stage loader menu was to isolate codes relevant to making the stages fast (as if ILs) in one place, but it being context-dependent codes only also makes sense and makes my suggestion redundant. That would make the basic code selection for fast IWs the stage loader, Piantissimo code and timer.

That's everything then, nice one.
